#!/bin/sh

FMTCMD="cargo +nightly fmt -- --check"

# Redirect output to stderr.
exec 1>&2

unset RUST_LOG

set -e
# crates in the workspace exclude list must be checked individually
for excluded in $(./scripts/list-excluded Cargo.toml); do
    (cd $excluded && $FMTCMD)
done

# check everything else
$FMTCMD
