#!/bin/bash

set -e

#llvm-cov show  \
#    --format=html -Xdemangler=rustfilt \
#     ./target/x86_64-unknown-linux-gnu/coverage/x86_64-unknown-linux-gnu/release/push_decoder \
#    -instr-profile=coverage/push_decoder/coverage.profdata \
#    > index.html

mkdir -p cov
kcov ./cov ./target/x86_64-unknown-linux-gnu/release/channel corpus/channel/*
