#!/bin/bash

set -e

# requires:
# - `cargo install cargo-kcov`

mkdir -p coverage
export RUSTFLAGS=--cfg=fuzzing
cargo build --bin channel
kcov --exclude-pattern=/usr/include,.cargo/registry ./coverage ./target/debug/channel corpus/channel/*

echo "coverage generated in ./coverage/index.html"
