#!/bin/sh

if [ -f /etc/redhat-release ] ; then
    dnf install gcc-arm-linux-gnu qemu-system-arm
elif [ -f /etc/debian_version ] ; then
    apt install gcc-arm-none-eabi qemu-system-arm gdb-multiarch
fi
