#!/bin/bash

set -e
set -x

# Note that some of these need additional cargo components installed for build - see respective READMEs

cargo build

(cd lightning-storage-server && cargo build)

(cd vls-signer-stm32 && cargo +nightly build --features stm32f413,debug --release --bin demo_signer)

(cd embedded && cargo +nightly build --target thumbv7m-none-eabi)
