#!/bin/bash

set -e
set -x

# Note that some of these need additional cargo components installed for build - see respective READMEs

cargo build --features system-test,redb-kvv

(cd lightning-storage-server && cargo build)

(cd vls-signer-stm32 && cargo +nightly-2024-10-13 build --features stm32f413,debug,developer --release --bin demo_signer)

(cd embedded && cargo +nightly-2024-10-13 build --target thumbv7m-none-eabi)
(cd wasm && cargo build)

