#!/bin/sh

# Where is the githooks directory for this repository?
GITHOOKSDIR=$(git rev-parse --git-path hooks)

# Construct a relative path for the pre-commit script
PRECOMMIT=$(realpath .githooks/pre-commit)
RELPATH=$(realpath --relative-to=$GITHOOKSDIR $PRECOMMIT)

# Make sure we are invoking from the correct place
if [ ! -f $PRECOMMIT ]; then
    echo "$PRECOMMIT not found; you need to be in the top-level directory"
    exit 1
fi

# Make a relative symbolic link
echo "Making link to $RELPATH in $(realpath $GITHOOKSDIR)"
(cd $GITHOOKSDIR && ln -fs $RELPATH)
