#!/bin/sh

# Where is the githooks directory for this repository?
GITHOOKSDIR=$(git rev-parse --git-path hooks)

# Construct a relative path for the pre-commit script
ABSOLUTE_PATH=$(realpath .githooks/pre-commit)

# Make sure we are invoking from the correct place
if [ ! -f $PRECOMMIT ]; then
    echo "$PRECOMMIT not found; you need to be in the top-level directory"
    exit 1
fi

# Make a relative symbolic link
echo "Making link to $ABSOLUTE_PATH in $GITHOOKSDIR)"
ln -fs $ABSOLUTE_PATH $GITHOOKSDIR/
