#!/bin/bash

set -e
set -x

CARGO="cargo +nightly-2024-10-13"

# Note that some of these need additional cargo components installed for build - see respective READMEs

$CARGO fmt --all "$@"

(cd lightning-storage-server && $CARGO fmt "$@")

(cd vls-signer-stm32 && $CARGO fmt "$@")

(cd embedded && $CARGO fmt "$@")
(cd wasm && $CARGO fmt "$@")
(cd fuzz && $CARGO fmt "$@")
