#!/bin/sh

export CARGO_TARGET_DIR=target/kcov

cargo kcov \
  --verbose \
  --test functional_test \
  --all \
  -- \
  --verify \
  --exclude-pattern=$HOME/.cargo,$HOME/.rustup,/usr/include,/usr/src/debug
