#!/bin/bash

set -e

export VLS_DISABLE_UPDATE_VERSION=0

# increases coverage
export RUST_LOG=debug

echo "Running coverage over everything ..."
cargo llvm-cov --no-report --workspace $@

# Always ignore some things
ALWAYS_IGNORE_ARRAY=(
    '_tests'
    '\/vls-core-test\/'
    'vls-core/src/util/loopback.rs'
    '\/lightning-storage-server\/'
)
IGNORE=$(IFS='|'; echo "${ALWAYS_IGNORE_ARRAY[*]}")

echo "Generating cobertura report over everything ..."
cargo llvm-cov report \
      --cobertura \
      --hide-instantiations \
      --ignore-filename-regex="$IGNORE" \
      --output-path=target/cobertura.xml

echo "Generating codecov.io report over everything ..."
cargo llvm-cov report \
      --codecov \
      --hide-instantiations \
      --ignore-filename-regex="$IGNORE" \
      --output-path=target/codecov.json

echo "Generating html report over everything ..."
cargo llvm-cov report \
      --html \
      --hide-instantiations \
      --ignore-filename-regex="$IGNORE" \
      --output-dir=target/llvm-cov/all/

# Additional reports want to focus on only core components
CORE_IGNORE_ARRAY=(
    "${ALWAYS_IGNORE_ARRAY[@]}"
    '\/bolt-derive\/'
    '\/vls-frontend\/'
    '\/vls-proxy\/'
    '\/vls-protocol\/'
    '\/vls-protocol-client\/'
    '\/vls-protocol-signer\/'
    '\/vls-persist\/'
)
IGNORE=$(IFS='|'; echo "${CORE_IGNORE_ARRAY[*]}")

echo "Generating html report for core components ..."
cargo llvm-cov report \
      --html \
      --hide-instantiations \
      --ignore-filename-regex="$IGNORE" \
      --output-dir=target/llvm-cov/core/

echo "Generating text summary report for core components ..."
cargo llvm-cov report \
      --hide-instantiations \
      --ignore-filename-regex="$IGNORE"

echo "Extracting the core line coverage percentage ..."
COV_OUTPUT=$(cargo llvm-cov report \
                   --json \
                   --hide-instantiations \
                   --ignore-filename-regex="$IGNORE")
CORE_LINE_COVERAGE=$(echo "$COV_OUTPUT" | jq '.data[0].totals.lines.percent')
echo "CORE_LINE_COVERAGE: $CORE_LINE_COVERAGE"
