#!/bin/bash

set -e

export CARGO_TARGET_DIR=target/kcov
export VLS_DISABLE_UPDATE_VERSION=0

cargo_kcov_args="$*"

run_kcov()
{
    cargo kcov \
          --verbose \
          $cargo_kcov_args \
          --output="target/kcov/cov" \
          --all \
          $* \
          -- \
          --verify \
          --exclude-region="kcov-ignore-start:kcov-ignore-end" \
          --exclude-pattern=$HOME/.cargo,$HOME/.rustup,/usr/include,/usr/src/debug
}

run_kcov --features test_utils
