[package]
name = "vls-frontend"
version = "0.14.0-rc.2"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2021"
license = "Apache-2.0"
description = "A library for implementing VLS frontend functions."
homepage = "https://gitlab.com/lightning-signer/docs/"
repository = "https://gitlab.com/lightning-signer/validating-lightning-signer"
rust-version = "1.74.0"

[features]
default = ["debug"]
test_utils = ["vls-core/test_utils"]
debug = []
log_pretty_print = ["vls-core/log_pretty_print"]

[lib]
name = "vls_frontend"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
log = { version="0.4.14", features = [ "std" ] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
url = { workspace = true }
vls-core = { path = "../vls-core", version = "0.14.0-rc.2", features = ["txoo-source"] }
lightning-storage-server = { path = "../lightning-storage-server/lib", version = "0.5.0", default-features = false }
triggered = "0.1"

[dependencies.txoo-bitcoind-client]
workspace = true
features = ["dummy-source"]

[dev-dependencies]
test-log = { workspace = true }
env_logger = { workspace = true }

[[example]]
name = "lss_example"
